<a href="https://colab.research.google.com/github/Hany-Kim/DataPreprocessing_and_SearchLibrary_KOSA/blob/main/DAY_24_05_20/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 넘파이를 이용한 다차원 배열 다루기

In [2]:
import numpy as np

## 1.0. 버전 확인

In [3]:
np.__version__

'1.25.2'

## 1.1. 자주 쓰는 함수

### arange() : range()와 유사, 배열을 만들때 사용

In [4]:
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### reshape() : 객체 모양 변환

1차원 배열 형태이던 A객체를 (3,5) 배열형태로 변환

In [5]:
A = np.arange(15).reshape(3,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### ndim : 현재 객체의 차원

n - dimession : A객체의 차원수를 출력

In [6]:
A.ndim

2

### shape() : 현재 객체의 모양

객체의 배열 형태를 튜플로 출력

In [7]:
A.shape

(3, 5)

In [8]:
B = np.arange(24).reshape(2,3,4)
print(B)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [11]:
B.shape

(2, 3, 4)

### size : 배열의 원소수 출력

In [9]:
print(A.size, B.size)

15 24


### dtype : A객체의 원소 타입을 출력

In [10]:
print(A.dtype)

int64


#### itemsize : int64 => 8byte

In [12]:
print(A.itemsize)

8


#### dtype 변환
type을 바꿀때는 =으로 하는 것이 아니라 astype함수를 사용해야한다.

타입이 바뀌면서 값이 전혀 예상치 못한 값으로 바뀜

In [14]:
A.dtype = np.int32
print(A)

[[ 0  0  1  0  2  0  3  0  4  0]
 [ 5  0  6  0  7  0  8  0  9  0]
 [10  0 11  0 12  0 13  0 14  0]]


#### 리스트 생성하기

In [15]:
A = np.array([2,3,4])
print(A)

[2 3 4]


#### 실수를 원소로 넣으면 알아서 float타입으로 생성됨

In [16]:
B = np.array([1.2, 3.5, 5.1])
print(B)
print(B.dtype)

[1.2 3.5 5.1]
float64


#### dtype=complex : 복소수

In [17]:
C = np.array([[1,2], [3,4]])
type(C.dtype)

numpy.dtypes.Int64DType

In [59]:
C = np.array([[1,2], [3,4]], dtype=complex)
type(C.dtype)
print(C)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


#### C를 복사

In [20]:
D = np.array(C)
print(D)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


D에 C를 그대로 담으면 D는 C를 바라보지만, 메모리가 다른 메모리에 저장되어 있음

In [21]:
print(id(C), id(D))

133672332800144 133672332779152


copy=True를 해야 같은 메모리를 사용함

In [23]:
DD = np.array(C, copy=True)

In [24]:
print(id(C), id(DD))

133672332800144 133672332731344


### 특정 수로 배열 생성

In [25]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 마지막에 .ones를 실행시켜서 메모리에 값이 저장되어 1이 출력되지만, 실제로는 무엇이 저장되어 있을지 모름

In [27]:
print(np.empty((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
print(np.ones(3))

[1. 1. 1.]


In [31]:
print(np.ones((3, )))

[1. 1. 1.]


### arange()
시작만 포함, 지정한 간격만큼 마지막 원소보다 작은 수까지 출력됨.

In [33]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [36]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

### linspace()
시작과 끝을 포함해, 지정한 갯수만큼 균등하게 간격을 나눔

In [37]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

### 배열 변환

In [38]:
A = np.arange(12).reshape(3,4)

In [39]:
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
A.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [41]:
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
A = A.reshape(2,6)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### -1은 나머지는 알아서 해달라는 의미

In [43]:
A.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
A.shape

(2, 6)

### 반환된는 값의 유무

코드 실행 후 print가 아닌 출력값이 있다면,
현재 객체는 그대로지만, 표시되는 값(또는 형태 등등)이 현재 객체와 다른 것이고

코드 실행 후 출력되는 값이 없다면,
현재 객체의 값(또는 형태)에 변화가 있다는 의미다.

In [47]:
A.resize(3,4) # 반환되는 값이 없다면, 현재 객체가 바뀐것
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
A.T # 반환되는 값이 출력되는 것으로 보아, 현재 객체는 바뀌지 않음

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])